# This file contains the credentials for the voice & chat platforms
# which your bot is using.
# https://rasa.com/docs/rasa/user-guide/messaging-and-voice-channels/

connectors.MachaaoConnector.MachaaoInputChannel:
  api_token: "<API Token>"
  base_url: "https://ganglia-dev.machaao.com"
